"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Heading } from "@/components/ui/heading";
import { PasswordInput } from "@/components/ui/password-input";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

type Status = "verifying" | "ready" | "invalid";

/**
 * Reached via the password-reset email link, which Supabase appends a
 * PKCE `?code=` to. Exchanged explicitly here (rather than relying on the
 * client's automatic detectSessionInUrl) so the failure/loading states are
 * visible instead of silent. This only works because the code_verifier was
 * generated by the BROWSER client on the forgot-password page — see the
 * comment there for why a server-issued request can't complete this.
 */
export function ResetPasswordContent() {
  const router = useRouter();
  const code = useSearchParams().get("code");
  const [status, setStatus] = useState<Status>(code ? "verifying" : "invalid");
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (!code) return;

    const supabase = createSupabaseBrowserClient();
    supabase.auth.exchangeCodeForSession(code).then(({ error: exchangeError }) => {
      setStatus(exchangeError ? "invalid" : "ready");
    });
  }, [code]);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError(null);

    if (password.length < 6) {
      setError("Password must be at least 6 characters.");
      return;
    }
    if (password !== confirm) {
      setError("Passwords don't match.");
      return;
    }

    setSubmitting(true);
    const supabase = createSupabaseBrowserClient();
    const { error: updateError } = await supabase.auth.updateUser({ password });
    setSubmitting(false);

    if (updateError) {
      setError("Something went wrong. Please request a new reset link.");
      return;
    }

    router.replace("/home");
  }

  if (status === "verifying") {
    return (
      <div className="flex flex-1 items-center justify-center">
        <p className="text-navy-500">Verifying your link…</p>
      </div>
    );
  }

  if (status === "invalid") {
    return (
      <div className="mx-auto flex w-full max-w-sm flex-1 flex-col items-center justify-center gap-4 px-6 py-16 text-center">
        <Heading level={2}>This link has expired</Heading>
        <p className="text-navy-600">
          Password reset links can only be used once. Request a new one from
          the login page.
        </p>
      </div>
    );
  }

  return (
    <div className="mx-auto flex w-full max-w-sm flex-1 flex-col justify-center gap-8 px-6 py-16">
      <Heading level={2} className="text-center">
        Set a new password
      </Heading>
      <form onSubmit={handleSubmit} className="flex flex-col gap-4">
        <PasswordInput
          label="New password"
          name="password"
          autoComplete="new-password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />
        <PasswordInput
          label="Confirm new password"
          name="confirm"
          autoComplete="new-password"
          value={confirm}
          onChange={(e) => setConfirm(e.target.value)}
          required
        />
        {error && <p className="text-sm text-red-600">{error}</p>}
        <Button type="submit" disabled={submitting}>
          {submitting ? "Updating…" : "Update password"}
        </Button>
      </form>
    </div>
  );
}
