"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Heading } from "@/components/ui/heading";
import { PasswordInput } from "@/components/ui/password-input";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

type Status = "confirm" | "verifying" | "ready" | "invalid";

/**
 * Reached via the password-reset email link, in one of two forms:
 *
 * 1. `?token_hash=…&type=recovery` (current email template). The token is
 *    ONLY redeemed when the user clicks "Continue" — never on page load or in
 *    an effect — because email security scanners open links in advance, and
 *    a plain GET must not use up the one-time token. Needs no PKCE
 *    code_verifier, so it also works on a different device.
 * 2. `?code=…` (the previous PKCE link, kept so emails already sent keep
 *    working). Supabase's own /verify already redeemed the token before this
 *    page loaded, so exchanging it here on load is unchanged behaviour.
 *    Exchanged explicitly (rather than relying on the client's automatic
 *    detectSessionInUrl) so the failure/loading states are visible instead
 *    of silent. This only works because the code_verifier was generated by
 *    the BROWSER client on the forgot-password page — see the comment there
 *    for why a server-issued request can't complete this.
 */
export function ResetPasswordContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const code = searchParams.get("code");
  const tokenHash = searchParams.get("type") === "recovery" ? searchParams.get("token_hash") : null;
  const [status, setStatus] = useState<Status>(code ? "verifying" : tokenHash ? "confirm" : "invalid");
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (!code) return;

    const supabase = createSupabaseBrowserClient();
    supabase.auth.exchangeCodeForSession(code).then(({ error: exchangeError }) => {
      setStatus(exchangeError ? "invalid" : "ready");
    });
  }, [code]);

  async function handleContinue() {
    if (!tokenHash) return;
    setStatus("verifying");

    const supabase = createSupabaseBrowserClient();
    const { error: verifyError } = await supabase.auth.verifyOtp({ token_hash: tokenHash, type: "recovery" });
    // The token is spent either way: drop it from the address bar and history.
    window.history.replaceState(null, "", "/reset-password");
    setStatus(verifyError ? "invalid" : "ready");
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError(null);

    if (password.length < 6) {
      setError("Password must be at least 6 characters.");
      return;
    }
    if (password !== confirm) {
      setError("Passwords don't match.");
      return;
    }

    setSubmitting(true);
    const supabase = createSupabaseBrowserClient();
    const { error: updateError } = await supabase.auth.updateUser({ password });
    setSubmitting(false);

    if (updateError) {
      setError("Something went wrong. Please request a new reset link.");
      return;
    }

    router.replace("/home");
  }

  if (status === "confirm") {
    return (
      <div className="mx-auto flex w-full max-w-sm flex-1 flex-col items-center justify-center gap-4 px-6 py-16 text-center">
        <Heading level={2}>Reset your password</Heading>
        <p className="text-navy-600">Continue to choose a new password for your Felyn account.</p>
        <Button type="button" onClick={handleContinue} className="self-stretch">
          Continue
        </Button>
      </div>
    );
  }

  if (status === "verifying") {
    return (
      <div className="flex flex-1 items-center justify-center">
        <p className="text-navy-500">Verifying your link…</p>
      </div>
    );
  }

  if (status === "invalid") {
    return (
      <div className="mx-auto flex w-full max-w-sm flex-1 flex-col items-center justify-center gap-4 px-6 py-16 text-center">
        <Heading level={2}>This link has expired</Heading>
        <p className="text-navy-600">
          Password reset links can only be used once. Request a new one from
          the login page.
        </p>
      </div>
    );
  }

  return (
    <div className="mx-auto flex w-full max-w-sm flex-1 flex-col justify-center gap-8 px-6 py-16">
      <Heading level={2} className="text-center">
        Set a new password
      </Heading>
      <form onSubmit={handleSubmit} className="flex flex-col gap-4">
        <PasswordInput
          label="New password"
          name="password"
          autoComplete="new-password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />
        <PasswordInput
          label="Confirm new password"
          name="confirm"
          autoComplete="new-password"
          value={confirm}
          onChange={(e) => setConfirm(e.target.value)}
          required
        />
        {error && <p className="text-sm text-red-600">{error}</p>}
        <Button type="submit" disabled={submitting}>
          {submitting ? "Updating…" : "Update password"}
        </Button>
      </form>
    </div>
  );
}
