"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { Heading } from "@/components/ui/heading";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

type Status = "verifying" | "invalid";

/**
 * Landing point for the signup-confirmation email link, which Supabase
 * appends a PKCE `?code=` to. Exchanges it for a session client-side
 * (this only works because signup's code_verifier was generated by the
 * browser client — see the comment in signup-form.tsx), then sends the
 * now-signed-in user into the app.
 */
export function CallbackContent() {
  const router = useRouter();
  const code = useSearchParams().get("code");
  const [status, setStatus] = useState<Status>(code ? "verifying" : "invalid");

  useEffect(() => {
    if (!code) return;

    const supabase = createSupabaseBrowserClient();
    supabase.auth.exchangeCodeForSession(code).then(({ error }) => {
      if (error) {
        setStatus("invalid");
        return;
      }
      router.replace("/home");
    });
  }, [code, router]);

  if (status === "invalid") {
    return (
      <div className="mx-auto flex w-full max-w-sm flex-1 flex-col items-center justify-center gap-4 px-6 py-16 text-center">
        <Heading level={2}>This link has expired</Heading>
        <p className="text-navy-600">
          Confirmation links can only be used once. Log in and we&apos;ll
          help you request a new one.
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-1 items-center justify-center">
      <p className="text-navy-500">Confirming your account…</p>
    </div>
  );
}
