"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Heading } from "@/components/ui/heading";
import { mobileStepHref } from "@/lib/contact/constants";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

type Status = "confirm" | "verifying" | "invalid";

/**
 * Landing point for the signup-confirmation email link, in one of two forms:
 *
 * 1. `?token_hash=…&type=email` (current Confirm signup template). The token
 *    is ONLY redeemed when the user clicks "Confirm my email" — never on page
 *    load or in an effect — because email security scanners open links in
 *    advance, and a plain GET must not use up the one-time token. Needs no
 *    PKCE code_verifier, so it also works on a different device.
 * 2. `?code=…` (the previous PKCE link, kept for emails already sent and for
 *    the email-change flow). Supabase's own /verify already redeemed the
 *    token before this page loaded, so it is exchanged on load as before —
 *    this only works because signup's code_verifier was generated by the
 *    browser client (see the comment in signup-form.tsx).
 *
 * Either way the now-signed-in user is sent on by host_intent, unchanged,
 * via /account/mobile, which saves the mobile number given at signup (it
 * couldn't be saved before the account had a session).
 */
export function CallbackContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const code = searchParams.get("code");
  const tokenHash = searchParams.get("type") === "email" ? searchParams.get("token_hash") : null;
  const [status, setStatus] = useState<Status>(code ? "verifying" : tokenHash ? "confirm" : "invalid");

  useEffect(() => {
    if (!code) return;

    const supabase = createSupabaseBrowserClient();
    supabase.auth.exchangeCodeForSession(code).then(({ data, error }) => {
      if (error) {
        setStatus("invalid");
        return;
      }
      // host_intent (set at /signup?intent=host) only picks the landing
      // page. /host/apply re-checks everything server-side from the database.
      const hostIntent = data.user?.user_metadata?.host_intent === true;
      router.replace(mobileStepHref(hostIntent ? "/host/apply" : "/home"));
    });
  }, [code, router]);

  async function handleConfirm() {
    if (!tokenHash) return;
    setStatus("verifying");

    const supabase = createSupabaseBrowserClient();
    const { data, error } = await supabase.auth.verifyOtp({ token_hash: tokenHash, type: "email" });
    // The token is spent either way: drop it from the address bar and history.
    window.history.replaceState(null, "", window.location.pathname);
    if (error) {
      setStatus("invalid");
      return;
    }
    // Same landing as the ?code= branch above: navigation only.
    const hostIntent = data.user?.user_metadata?.host_intent === true;
    router.replace(mobileStepHref(hostIntent ? "/host/apply" : "/home"));
  }

  if (status === "confirm") {
    return (
      <div className="mx-auto flex w-full max-w-sm flex-1 flex-col items-center justify-center gap-4 px-6 py-16 text-center">
        <Heading level={2}>Confirm your email</Heading>
        <p className="text-navy-600">Click below to confirm your email address and activate your Felyn account.</p>
        <Button type="button" onClick={handleConfirm} className="self-stretch">
          Confirm my email
        </Button>
      </div>
    );
  }

  if (status === "invalid") {
    return (
      <div className="mx-auto flex w-full max-w-sm flex-1 flex-col items-center justify-center gap-4 px-6 py-16 text-center">
        <Heading level={2}>This link has expired</Heading>
        <p className="text-navy-600">
          Confirmation links can only be used once. Log in and we&apos;ll
          help you request a new one.
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-1 items-center justify-center">
      <p className="text-navy-500">Confirming your account…</p>
    </div>
  );
}
